name: terraform-CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: terraform
          path: ${{ github.workspace }}//appservice
          

  deploy-dev-infra:
    name: Deploy Infra Dev
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/appservice
        
    environment:
      name: dev
      

    
